feat(1530): changed to remote couchdb with caching
1-Platform/idea-hub pull request #9
Opened 2021-10-01 07:50 UTC by akhilmhdh

# Closes
1. 1530

# Explain the feature/fix

1. Changed to remote couchdb
2. Implemented caching
3. Fixed ui of comment submit
4. Fixed change feed issue

## Does this PR introduce a breaking change

Yes

## Screenshots

<details>
<summary>View Screenshots</summary>

Except comment box no ui changes

| Description | Screenshot |
| - | - |
| Comment Box | <img width="855" alt="Screenshot 2021-09-27 at 3 10 31 PM" src="https://user-images.githubusercontent.com/31166322/135584520-416882c6-5fd0-49b6-9cdf-d8fc29a71c8a.png">
> |

</details
### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

2021-10-04 06:32 UTC, riginoommen approved these changes

2021-10-04 10:19 UTC, ghanlohar requested changes

2021-10-04 10:19 UTC, ghanlohar commented on src/pages/HomePage/hooks/useGetTagCountList.ts
> +  const isTagsLoading = !error && !tagCount;
Use Boolean() for this for readability.

2021-10-04 13:48 UTC, akhilmhdh commented on src/pages/HomePage/hooks/useGetTagCountList.ts
> +      subject: `Failed to fetch tags`,
Good catch!!

2021-10-04 13:50 UTC, akhilmhdh commented on src/containers/CommentsContainer/hooks/useGetComments.tsx
> +  const isCommentsLoading = !comments && !error;
@ghanlohar  Basically that would fire eslint error of redundancy.....i can change it to `!(comments && error)`. But i felt this makes more sense on reading like no comments and no error means loading

2021-10-04 13:51 UTC, akhilmhdh commented on src/containers/CommentsContainer/hooks/useGetComments.tsx
> +  const isCommentsLoading = !comments && !error;
Or did u mean vice versa...Boolean(!data) that would also fire redundant eslint error

2021-10-05 05:45 UTC, ghanlohar commented on src/containers/CommentsContainer/hooks/useGetComments.tsx
> +  const isCommentsLoading = !comments && !error;
Boolean(!data) would be lint-free but I think it's fine using it as it is.

2021-10-05 08:21 UTC, ghanlohar submitted a review, later dismissed

2021-10-06 07:07 UTC, deshmukhmayur requested changes

2021-10-06 07:07 UTC, deshmukhmayur commented on src/containers/CommentsContainer/components/CommentBox/CommentBox.tsx
> +            </CommentField.CommentButton> */}
Remove unused / commented statements.

2021-10-06 07:24 UTC, akhilmhdh commented on src/containers/CommentsContainer/CommentsContainer.tsx
> +  // }, []);
Done

2021-10-06 07:29 UTC, deshmukhmayur approved these changes

2021-10-06 07:35 UTC, riginoommen approved these changes

2021-10-06 07:39 UTC, merged